name: Rector

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'src/**.php'
      - 'composer.*'
      - 'rector.php'
      - '.github/workflows/test-rector.yml'
  push:
    branches:
      - dev
    paths:
      - 'src/**.php'
      - 'composer.*'
      - 'rector.php'
      - '.github/workflows/test-rector.yml'

jobs:
  build:
    name: PHP ${{ matrix.php-versions }} Rector Analysis
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpstan
          extensions: intl, json, mbstring, xml
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        run: echo "COMPOSER_CACHE_FILES_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_FILES_DIR }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          if [ -f composer.lock ]; then
            composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
          else
            composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
          fi

      - name: Analyze for refactoring
        run: vendor/bin/rector process --dry-run
